# Generated by Django 4.2.13 on 2025-08-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_media_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Watch Latest Movies & TV Shows', help_text='Default title for pages without specific titles', max_length=200)),
                ('site_name', models.CharField(default='Hypeblog9jaTV', max_length=100)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
